#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharedSquawk.Client.Droid.Resource", IsApplication=true)]

namespace SharedSquawk.Client.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bubble_green = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubble_yellow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chat = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int empty_contact = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int green = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int grey = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int group = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int popup = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int settings = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int image = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int message = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int nick = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int nicknameAndTimeWrapper = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int wrapper = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int image_item_opponent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int image_item_owner = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int message_item_opponent = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int message_item_owner = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
