using SharedSquawk.Client.Model.Entities;
using System.Linq;

namespace SharedSquawk.Client.Model
{
    public class CountriesRepository
    {
		public static string Get(int countryId)
		{
			var item = _countries.Where(w => w.CountryId == countryId).FirstOrDefault();
			if (item == null)
			{
				return string.Empty;
			}
			else
			{
				return item.Name;
			}
		}

		public static Country[] GetAll ()
		{
			return _countries;
		}

		private static readonly Country[] _countries = new[]
                {
					new Country(176, "Afghanistan"),
					new Country(228, "Albania"),
					new Country(162, "Algeria"),
					new Country(274, "Andorra"),
					new Country(229, "Angola"),
					new Country(112, "Argentina"),
					new Country(186, "Armenia"),
					new Country(275, "Aruba"),
					new Country(105, "Australia"),
					new Country(144, "Austria"),
					new Country(204, "Azerbaijan"),
					new Country(177, "Bahamas"),
					new Country(172, "Bahrain"),
					new Country(167, "Bangladesh"),
					new Country(184, "Barbados"),
					new Country(199, "Belarus"),
					new Country(120, "Belgium"),
					new Country(214, "Belize"),
					new Country(230, "Benin"),
					new Country(231, "Bermuda"),
					new Country(191, "Bolivia"),
					new Country(168, "Bosnia-Herzegovina"),
					new Country(232, "Botswana"),
					new Country(113, "Brazil"),
					new Country(233, "Brunei"),
					new Country(157, "Bulgaria"),
					new Country(234, "Burkina Faso"),
					new Country(215, "Burma (Myanmar)"),
					new Country(235, "Burundi"),
					new Country(207, "Cambodia"),
					new Country(175, "Cameroon"),
					new Country(102, "Canada"),
					new Country(236, "Canary Islands"),
					new Country(218, "Cayman Islands"),
					new Country(225, "Central African Republic"),
					new Country(268, "Chad"),
					new Country(154, "Chile"),
					new Country(109, "China"),
					new Country(143, "Colombia"),
					new Country(211, "Congo"),
					new Country(173, "Costa Rica"),
					new Country(138, "Croatia"),
					new Country(210, "Cuba"),
					new Country(237, "Cyprus"),
					new Country(161, "Czech Republic"),
					new Country(150, "Denmark"),
					new Country(239, "Djibouti"),
					new Country(197, "Dominican Republic"),
					new Country(183, "Ecuador"),
					new Country(131, "Egypt"),
					new Country(200, "El Salvador"),
					new Country(244, "Equatorial Guinea"),
					new Country(182, "Estonia"),
					new Country(178, "Ethiopia"),
					new Country(140, "Finland"),
					new Country(104, "France"),
					new Country(247, "French Guiana"),
					new Country(240, "Gabon"),
					new Country(241, "Gambia"),
					new Country(194, "Georgia"),
					new Country(108, "Germany"),
					new Country(148, "Ghana"),
					new Country(242, "Gibraltar"),
					new Country(139, "Greece"),
					new Country(208, "Guatemala"),
					new Country(243, "Guinea"),
					new Country(245, "Guinea-Bissau"),
					new Country(246, "Guyana"),
					new Country(203, "Haiti"),
					new Country(209, "Honduras"),
					new Country(136, "Hong Kong"),
					new Country(155, "Hungary"),
					new Country(189, "Iceland"),
					new Country(103, "India"),
					new Country(132, "Indonesia"),
					new Country(114, "Iran"),
					new Country(181, "Iraq"),
					new Country(129, "Ireland"),
					new Country(145, "Israel"),
					new Country(111, "Italy"),
					new Country(238, "Ivory Coast"),
					new Country(169, "Jamaica"),
					new Country(107, "Japan"),
					new Country(164, "Jordan"),
					new Country(216, "Kazakhstan"),
					new Country(156, "Kenya"),
					new Country(163, "Kuwait"),
					new Country(248, "Kyrgyzstan"),
					new Country(219, "Laos"),
					new Country(187, "Latvia"),
					new Country(159, "Lebanon"),
					new Country(249, "Lesotho"),
					new Country(212, "Liberia"),
					new Country(250, "Libya"),
					new Country(269, "Liechtenstein"),
					new Country(170, "Lithuania"),
					new Country(201, "Luxembourg"),
					new Country(195, "Macedonia"),
					new Country(251, "Madagascar"),
					new Country(217, "Malawi"),
					new Country(110, "Malaysia"),
					new Country(226, "Maldives"),
					new Country(252, "Mali"),
					new Country(192, "Malta"),
					new Country(253, "Mauritania"),
					new Country(180, "Mauritius"),
					new Country(119, "Mexico"),
					new Country(224, "Moldova"),
					new Country(254, "Monaco"),
					new Country(255, "Mongolia"),
					new Country(149, "Morocco"),
					new Country(227, "Mozambique"),
					new Country(256, "Namibia"),
					new Country(257, "Nepal"),
					new Country(124, "Netherlands"),
					new Country(258, "New Caledonia"),
					new Country(125, "New Zealand"),
					new Country(222, "Nicaragua"),
					new Country(206, "Niger"),
					new Country(147, "Nigeria"),
					new Country(223, "North Korea"),
					new Country(146, "Norway"),
					new Country(190, "Oman"),
					new Country(117, "Pakistan"),
					new Country(188, "Panama"),
					new Country(260, "Papua New Guinea"),
					new Country(220, "Paraguay"),
					new Country(142, "Peru"),
					new Country(116, "Philippines"),
					new Country(126, "Poland"),
					new Country(152, "Portugal"),
					new Country(160, "Puerto Rico"),
					new Country(193, "Qatar"),
					new Country(261, "Reunion Island"),
					new Country(135, "Romania"),
					new Country(123, "Russia"),
					new Country(262, "Rwanda"),
					new Country(134, "Saudi Arabia"),
					new Country(130, "Scotland"),
					new Country(263, "Senegal"),
					new Country(276, "Serbia"),
					new Country(264, "Sierra Leone"),
					new Country(118, "Singapore"),
					new Country(174, "Slovakia"),
					new Country(165, "Slovenia"),
					new Country(213, "Somalia"),
					new Country(137, "South Africa"),
					new Country(127, "South Korea"),
					new Country(106, "Spain"),
					new Country(221, "Sri Lanka"),
					new Country(196, "Sudan"),
					new Country(265, "Surinam"),
					new Country(266, "Swaziland"),
					new Country(133, "Sweden"),
					new Country(141, "Switzerland"),
					new Country(171, "Syria"),
					new Country(121, "Taiwan"),
					new Country(267, "Tajikistan"),
					new Country(166, "Tanzania"),
					new Country(122, "Thailand"),
					new Country(270, "Togo"),
					new Country(277, "Trinidad and Tobago"),
					new Country(179, "Tunisia"),
					new Country(115, "Turkey"),
					new Country(271, "Turkmenistan"),
					new Country(259, "Uganda"),
					new Country(202, "Ukraine"),
					new Country(128, "United Arab Emirates"),
					new Country(101, "United Kingdom"),
					new Country(100, "United States"),
					new Country(185, "Uruguay"),
					new Country(205, "Uzbekistan"),
					new Country(153, "Venezuela"),
					new Country(151, "Vietnam"),
					new Country(272, "Yemen"),
					new Country(158, "Yugoslavia"),
					new Country(273, "Zambia"),
					new Country(198, "Zimbabwe")

                };
        
    }
}
